@Tags(['regression', 'slow'])
library;
// Regression test for issue #341 (4th route/view contract churn after
// #328 → #331 → #333 → #335):
// https://github.com/arrrrny/zuraffa/issues/341
//
// Two defects:
//
//   A. The route generator emitted routes for VALUE OBJECTS. An entity
//      re-modeled as a value object (`@Zorphy(kind: ZorphyKind.valueObject)`,
//      embedded in a parent entity, no id, no CRUD) has no view — but
//      `zfa route create <VO>` still emitted `<vo>_routes.dart` importing
//      and referencing a non-existent `<Vo>View` (uri_does_not_exist +
//      undefined_function). The route generator must skip value objects,
//      and clean up stale routes left by runs from before the re-model.
//
//   B. PR #340 (#336) regressed the route/view constructor contract:
//      `zfa make` regenerates views with an empty methods list (methods
//      are owned by the usecase plugins), which drops the entity
//      named-param from the view constructor — while routes kept emitting
//      `View(entityCamel: state.extra as Entity?)`. Whichever generator
//      wins, the two must agree.
//
// Fix (#341):
//   - route_builder.dart probes the entity source: value objects skip
//     route generation entirely and trigger cleanup of stale artifacts.
//   - route_builder.dart probes the view files on disk and only passes
//     named-params their constructors actually accept (`this.<param>`),
//     keeping the route aligned with however the view was regenerated.
//
// This is the SHARED contract test the issue asked for: it generates
// views + routes together in one fixture and asserts every named-param
// passed by a route's view constructor call is accepted by that view.
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../helpers/vpc_test_utils.dart';
import 'package:zuraffa/src/core/generator_options.dart';
import 'package:zuraffa/src/models/generator_config.dart';
import 'package:zuraffa/src/plugins/route/builders/route_builder.dart';
import 'package:zuraffa/src/plugins/view/view_plugin.dart';

void main() {
  late Directory tempDir;
  late String outputDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('zuraffa_issue341_');
    outputDir = Directory('${tempDir.path}/lib/src').path;
    // Declare a Flutter pubspec so the VPC generators run on their
    // intended target instead of relying on the no-pubspec
    // (unknown flavour) fallback — issues #431 / #435.
    await writeFlutterPubspecAt(tempDir.path);
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      await tempDir.delete(recursive: true);
    }
  });

  const generatorOptions = GeneratorOptions(
    dryRun: false,
    force: true,
    verbose: false,
  );

  // ─────────────────────────────────────────────────────────────────
  // Bug A: route generator must skip value objects
  // ─────────────────────────────────────────────────────────────────

  group('issue #341 A — route generator skips value objects', () {
    Future<void> writeValueObjectEntity() async {
      final entityDir = Directory(
        '$outputDir/domain/entities/customer_profile',
      );
      await entityDir.create(recursive: true);
      await File('${entityDir.path}/customer_profile.dart').writeAsString('''
// Auto-generated by Zorphy
import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'customer_profile.zorphy.dart';

@Zorphy(kind: ZorphyKind.valueObject, generateJson: true)
abstract class \$CustomerProfile {
  int? get yearOfBirth;
  String? get shoppingStyle;
}
''');
    }

    test('route generation for a value object emits NO routes file', () async {
      await writeValueObjectEntity();

      final builder = RouteBuilder(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await builder.generate(
        GeneratorConfig(
          name: 'CustomerProfile',
          methods: const ['get', 'getList'],
          generateVpcs: true,
          generateRoute: true,
          outputDir: outputDir,
        ),
      );

      final routesFile = File(
        '$outputDir/routing/customer_profile_routes.dart',
      );
      expect(
        routesFile.existsSync(),
        isFalse,
        reason:
            'value objects are embedded composition types with no view — '
            'the route generator must not emit routes for them (#341).',
      );
    });

    test('route generation for a value object cleans up stale routes from '
        'before the re-model (routes file + app_routes + index)', () async {
      await writeValueObjectEntity();

      // Simulate stale artifacts from a run made while CustomerProfile
      // was still a regular entity with CRUD + view + routes.
      final routingDir = Directory('$outputDir/routing');
      await routingDir.create(recursive: true);
      await File(
        '${routingDir.path}/customer_profile_routes.dart',
      ).writeAsString('''
// Generated by zfa for: CustomerProfile
import 'package:go_router/go_router.dart';
import '../presentation/pages/customer_profile/customer_profile_view.dart';

abstract class CustomerProfileRoutes {
  static const String customerProfileList = '/customer_profile';
  static const String customerProfileDetail = '/customer_profile/:id';
}

List<GoRoute> customerProfileRoutes() {
  return [
    GoRoute(
      path: CustomerProfileRoutes.customerProfileList,
      name: 'customer_profile_list',
      builder: (context, state) =>
          const CustomerProfileView(),
    ),
  ];
}
''');
      await File('${routingDir.path}/app_routes.dart').writeAsString('''
// Generated by zfa
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import './index.dart';

class AppRoutes {
  static const String customerProfileList =
      CustomerProfileRoutes.customerProfileList;
  static const String customerProfileDetail =
      CustomerProfileRoutes.customerProfileDetail;
  static const String productList = ProductRoutes.productList;
}

extension RouterExtension on BuildContext {
  void goToCustomerProfileList() => go(AppRoutes.customerProfileList);
  void goToCustomerProfileDetail(String id) =>
      go('/customer_profile/\$id');
  void goToProductList() => go(AppRoutes.productList);
}
''');
      // Also a real product routes file so index.dart keeps content.
      await File('${routingDir.path}/product_routes.dart').writeAsString('''
// Generated by zfa for: Product
import 'package:go_router/go_router.dart';

abstract class ProductRoutes {
  static const String productList = '/product';
}

List<GoRoute> productRoutes() {
  return [
    GoRoute(
      path: ProductRoutes.productList,
      name: 'product_list',
      builder: (context, state) => const ProductView(),
    ),
  ];
}
''');

      final builder = RouteBuilder(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await builder.generate(
        GeneratorConfig(
          name: 'CustomerProfile',
          methods: const ['get', 'getList'],
          generateVpcs: true,
          generateRoute: true,
          outputDir: outputDir,
        ),
      );

      // The stale routes file must be deleted.
      expect(
        File('${routingDir.path}/customer_profile_routes.dart').existsSync(),
        isFalse,
        reason: 'stale <vo>_routes.dart must be deleted (#341).',
      );

      // app_routes.dart must drop the VO constants/extension methods,
      // keeping unrelated ones.
      final appRoutes = await File(
        '${routingDir.path}/app_routes.dart',
      ).readAsString();
      expect(appRoutes.contains('CustomerProfile'), isFalse);
      expect(appRoutes.contains('goToProductList'), isTrue);
      expect(appRoutes.contains('productList'), isTrue);

      // index.dart must no longer export/import the VO routes.
      final indexPath = '${routingDir.path}/index.dart';
      expect(File(indexPath).existsSync(), isTrue);
      final index = await File(indexPath).readAsString();
      expect(index.contains('customer_profile_routes.dart'), isFalse);
      expect(index.contains('product_routes.dart'), isTrue);
    });

    test('route generation still works for a REGULAR entity (no false VO '
        'skip)', () async {
      final builder = RouteBuilder(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await builder.generate(
        GeneratorConfig(
          name: 'Feedback',
          methods: const ['get', 'getList'],
          generateVpcs: true,
          generateRoute: true,
          outputDir: outputDir,
        ),
      );

      expect(
        File('$outputDir/routing/feedback_routes.dart').existsSync(),
        isTrue,
        reason:
            'regular (non-VO) entities must keep getting route files — '
            'the VO skip must not over-trigger.',
      );
    });
  });

  // ─────────────────────────────────────────────────────────────────
  // Bug B: route/view constructor contract after view regeneration
  // ─────────────────────────────────────────────────────────────────

  group('issue #341 B — route passes only params the view accepts', () {
    test('view regenerated WITHOUT the entity named-param (zfa make path: '
        'empty methods) — route must not pass it', () async {
      // Reproduce the zfa make regeneration shape: controller/presenter
      // generated, methods owned by usecases (empty here).
      final viewPlugin = ViewPlugin(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await viewPlugin.generate(
        GeneratorConfig(
          name: 'Feedback',
          methods: const [],
          generateView: true,
          generateController: true,
          generatePresenter: true,
          outputDir: outputDir,
        ),
      );

      final viewFile = File(
        '$outputDir/presentation/pages/feedback/feedback_view.dart',
      );
      expect(viewFile.existsSync(), isTrue);
      final viewContent = viewFile.readAsStringSync();
      // The regenerated view dropped the entity named-param — this is
      // the PR #340 regression premise.
      expect(viewContent.contains('this.feedback,'), isFalse);

      final builder = RouteBuilder(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await builder.generate(
        GeneratorConfig(
          name: 'Feedback',
          methods: const ['get', 'getList'],
          generateVpcs: true,
          generateRoute: true,
          outputDir: outputDir,
        ),
      );

      final routesContent = File(
        '$outputDir/routing/feedback_routes.dart',
      ).readAsStringSync();
      expect(
        routesContent.contains('feedback:'),
        isFalse,
        reason:
            'route must not pass the entity named-param when the '
            'regenerated view does not accept it (#341 defect 2 — was '
            'undefined_named_parameter on FeedbackView).',
      );
      // The entity import must be gone too (it would be unused).
      expect(
        routesContent.contains('../domain/entities/feedback/feedback.dart'),
        isFalse,
        reason:
            'entity import must be dropped when no route passes the '
            'entity named-param (would be an unused_import).',
      );
    });

    test('view WITH the entity named-param (route create path: explicit '
        'methods) — route keeps passing it', () async {
      final viewPlugin = ViewPlugin(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await viewPlugin.generate(
        GeneratorConfig(
          name: 'Feedback',
          methods: const ['get', 'update'],
          generateView: true,
          outputDir: outputDir,
        ),
      );

      final builder = RouteBuilder(
        outputDir: outputDir,
        options: generatorOptions,
      );
      await builder.generate(
        GeneratorConfig(
          name: 'Feedback',
          methods: const ['get', 'getList'],
          generateVpcs: true,
          generateRoute: true,
          outputDir: outputDir,
        ),
      );

      final routesContent = File(
        '$outputDir/routing/feedback_routes.dart',
      ).readAsStringSync();
      expect(
        routesContent.contains('feedback: (state.extra as Feedback?)'),
        isTrue,
        reason:
            'route must keep passing the entity named-param when the '
            'view accepts it (the #328 contract stays intact).',
      );
    });
  });

  // ─────────────────────────────────────────────────────────────────
  // The shared contract: generate routes + views together and assert
  // every named-param a route passes is accepted by the target view.
  // ─────────────────────────────────────────────────────────────────

  group('issue #341 — shared route/view contract (whack-a-mole stopper)', () {
    // Both generation shapes that have been flipping back and forth
    // across #328→#331→#333→#335→#341.
    final scenarios = <String, GeneratorConfig Function(String)>{
      'view from zfa route create (methods get,update)': (name) =>
          GeneratorConfig(
            name: name,
            methods: const ['get', 'update'],
            generateView: true,
            outputDir: outputDir,
          ),
      'view from zfa make (empty methods + vpc flags)': (name) =>
          GeneratorConfig(
            name: name,
            methods: const [],
            generateView: true,
            generateController: true,
            generatePresenter: true,
            outputDir: outputDir,
          ),
      'view with state (get,getList)': (name) => GeneratorConfig(
        name: name,
        methods: const ['get', 'getList'],
        generateView: true,
        generateState: true,
        outputDir: outputDir,
      ),
    };

    for (final entry in scenarios.entries) {
      test('route+view agree under: ${entry.key}', () async {
        const entityName = 'Product';
        final viewPlugin = ViewPlugin(
          outputDir: outputDir,
          options: generatorOptions,
        );
        await viewPlugin.generate(entry.value(entityName));

        final builder = RouteBuilder(
          outputDir: outputDir,
          options: generatorOptions,
        );
        await builder.generate(
          GeneratorConfig(
            name: entityName,
            methods: const ['get', 'getList', 'create', 'update'],
            generateVpcs: true,
            generateRoute: true,
            outputDir: outputDir,
          ),
        );

        final routingDir = Directory('$outputDir/routing');
        final viewFiles = routingDir
            .parent // lib/src
            .listSync(recursive: true)
            .whereType<File>()
            .where((f) => f.path.endsWith('_view.dart'))
            .toList();

        // View accepted params: every `this.<param>` in each view file.
        final acceptedByView = <String, Set<String>>{};
        for (final vf in viewFiles) {
          acceptedByView[pathBasenameNoExt(vf.path)] = RegExp(
            r'this\.\s*([a-zA-Z_][a-zA-Z0-9_]*)',
          ).allMatches(vf.readAsStringSync()).map((m) => m.group(1)!).toSet();
        }

        // Every view constructor call in the route files must only use
        // named-params the target view accepts.
        final routeFiles = routingDir
            .listSync()
            .whereType<File>()
            .where(
              (f) =>
                  f.path.endsWith('_routes.dart') &&
                  !f.path.endsWith('app_routes.dart') &&
                  !f.path.endsWith('index.dart'),
            )
            .toList();
        expect(routeFiles, isNotEmpty);

        final callPattern = RegExp(
          r'(ProductView|ProductDetailView)\(\s*([^)]*)\)',
          dotAll: true,
        );
        var checkedCalls = 0;
        for (final rf in routeFiles) {
          final content = rf.readAsStringSync();
          for (final match in callPattern.allMatches(content)) {
            checkedCalls++;
            final viewName = match.group(1)!;
            final argsSource = match.group(2)!;
            // Which view file is this? <entity>_view.dart vs
            // <entity>_detail_view.dart.
            final viewFileKey = viewName.endsWith('DetailView')
                ? 'product_detail_view'
                : 'product_view';
            final accepted = acceptedByView[viewFileKey];
            expect(
              accepted,
              isNotNull,
              reason:
                  'route calls `$viewName` but its view file was never '
                  'generated — routes must only reference views that '
                  'exist (#328/#333 contract).',
            );
            for (final argMatch in RegExp(
              r'([a-zA-Z_][a-zA-Z0-9_]*)\s*:',
            ).allMatches(argsSource)) {
              expect(
                accepted!.contains(argMatch.group(1)!),
                isTrue,
                reason:
                    'route passes `${argMatch.group(1)}:` to `$viewName` '
                    'but the view constructor does not accept it. This is '
                    'the #341 route/view contract mismatch.',
              );
            }
          }
        }
        expect(checkedCalls, greaterThan(0));
      });
    }
  });
}

String pathBasenameNoExt(String p) {
  final slash = p.lastIndexOf('/');
  final dot = p.lastIndexOf('.');
  var base = slash >= 0 ? p.substring(slash + 1) : p;
  if (dot > slash) base = base.substring(0, dot - slash - 1);
  return base;
}
