@Tags(['regression', 'slow'])
library;
// https://github.com/arrrrny/zuraffa/issues/359
//
// Before this fix, generated views rendered an empty `Container()` body
// — mock data existed (generated by `zfa mock <Entity>` / `zfa make
// Entity --mock`) but no generated screen consumed it. A freshly
// generated zfa-only app was not visibly functional.
//
// This test verifies the companion gap from issue #359: when a mock data
// file exists at `lib/src/data/mock/<entity>_mock_data.dart`, the
// generated view body renders a real list/detail of mock entities
// (ListView.builder over `<Entity>MockData.sampleList` for list views,
// Card with `<Entity>MockData.sample<Entity>` for detail views) instead
// of the empty `Container()`. When the mock file is absent, the view
// falls back to `Container()` so the contract stays backwards-compatible.
import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/diagnostic/diagnostic.dart';
import 'package:flutter_test/flutter_test.dart';

import '../helpers/vpc_test_utils.dart';
import 'package:zuraffa/src/core/generator_options.dart';
import 'package:zuraffa/src/models/generator_config.dart';
import 'package:zuraffa/src/plugins/view/view_plugin.dart';

void main() {
  late Directory tempDir;
  late String outputDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('issue_359_view_');
    outputDir = Directory('${tempDir.path}/lib/src').path;
    // Declare a Flutter pubspec so the VPC generators run on their
    // intended target instead of relying on the no-pubspec
    // (unknown flavour) fallback — issues #431 / #435.
    await writeFlutterPubspecAt(tempDir.path);
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      await tempDir.delete(recursive: true);
    }
  });

  /// Seeds a `<entity>_mock_data.dart` file matching the shape produced
  /// by the mock plugin (`MockDataBuilder.generateMockDataFile`):
  /// a `<Entity>MockData` class with `sampleList` + `sample<Entity>` getters.
  Future<void> seedMockData(String entityName, String entitySnake) async {
    final mockDir = Directory('$outputDir/data/mock');
    await mockDir.create(recursive: true);
    final mockFile = File('${mockDir.path}/${entitySnake}_mock_data.dart');
    final entityCamel = entityName[0].toLowerCase() + entityName.substring(1);
    await mockFile.writeAsString('''
import '../../domain/entities/$entitySnake/$entitySnake.dart';

class ${entityName}MockData {
  static final List<$entityName> ${entityCamel}s = const [];
  static $entityName get sample$entityName => ${entityCamel}s.first;
  static List<$entityName> get sampleList => ${entityCamel}s;
}
''');
  }

  group('issue #359 — generated views render mock data by default', () {
    test('list view body renders ListView.builder over '
        '<Entity>MockData.sampleList when mock data exists', () async {
      await seedMockData('Product', 'product');

      final plugin = ViewPlugin(
        outputDir: outputDir,
        options: const GeneratorOptions(dryRun: false, force: true),
      );
      final config = GeneratorConfig(
        name: 'Product',
        methods: const ['get', 'getList'],
        generateView: true,
        outputDir: outputDir,
      );
      final files = await plugin.generate(config);

      final listView = files
          .firstWhere((f) => f.path.contains('product_view.dart'))
          .content!;
      expect(
        listView.contains('ProductMockData'),
        isTrue,
        reason: 'view body must reference ProductMockData',
      );
      expect(
        listView.contains('sampleList'),
        isTrue,
        reason: 'list view must use sampleList',
      );
      expect(
        listView.contains('ListView.builder'),
        isTrue,
        reason: 'list view must render a ListView.builder',
      );
      expect(listView.contains('ListTile'), isTrue);
      expect(listView.contains('itemCount'), isTrue);
      expect(
        listView.contains("data/mock/product_mock_data.dart"),
        isTrue,
        reason: 'view must import the mock_data file',
      );
      expect(
        listView.contains('Container()'),
        isFalse,
        reason: 'no empty Container when mock data is available',
      );

      final errors = syntaxErrors(listView);
      expect(
        errors,
        isEmpty,
        reason:
            'list view must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
    });

    test('detail view body renders Card + ListTile with '
        '<Entity>MockData.sample<Entity> when mock data exists', () async {
      await seedMockData('Product', 'product');

      final plugin = ViewPlugin(
        outputDir: outputDir,
        options: const GeneratorOptions(dryRun: false, force: true),
      );
      final config = GeneratorConfig(
        name: 'Product',
        methods: const ['get', 'getList'],
        generateView: true,
        outputDir: outputDir,
      );
      final files = await plugin.generate(config);

      final detailView = files
          .firstWhere((f) => f.path.contains('product_detail_view.dart'))
          .content!;
      expect(detailView.contains('ProductMockData'), isTrue);
      expect(
        detailView.contains('sampleProduct'),
        isTrue,
        reason: 'detail view must use sample<Entity> getter',
      );
      expect(detailView.contains('Card'), isTrue);
      expect(detailView.contains('ListTile'), isTrue);
      expect(
        detailView.contains('Container()'),
        isFalse,
        reason: 'no empty Container when mock data is available',
      );

      final errors = syntaxErrors(detailView);
      expect(
        errors,
        isEmpty,
        reason:
            'detail view must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
    });

    test('view falls back to Container() when no mock data file exists '
        '(backwards-compatible)', () async {
      // No seedMockData — mock file absent.
      final plugin = ViewPlugin(
        outputDir: outputDir,
        options: const GeneratorOptions(dryRun: false, force: true),
      );
      final config = GeneratorConfig(
        name: 'Order',
        methods: const ['getList'],
        generateView: true,
        outputDir: outputDir,
      );
      final files = await plugin.generate(config);

      final content = files
          .firstWhere((f) => f.path.contains('order_view.dart'))
          .content!;
      expect(
        content.contains('Container()'),
        isTrue,
        reason: 'fallback to Container when mock data absent',
      );
      expect(
        content.contains('OrderMockData'),
        isFalse,
        reason: 'no mock reference when mock file absent',
      );
      expect(
        content.contains('data/mock/'),
        isFalse,
        reason: 'no mock import when mock file absent',
      );

      final errors = syntaxErrors(content);
      expect(
        errors,
        isEmpty,
        reason:
            'fallback view must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
    });

    test('view with --state renders mock data without an unused viewState '
        'declaration', () async {
      await seedMockData('Cart', 'cart');

      final plugin = ViewPlugin(
        outputDir: outputDir,
        options: const GeneratorOptions(dryRun: false, force: true),
      );
      final config = GeneratorConfig(
        name: 'Cart',
        methods: const ['getList'],
        generateView: true,
        generateState: true,
        outputDir: outputDir,
      );
      final files = await plugin.generate(config);

      final content = files
          .firstWhere((f) => f.path.contains('cart_view.dart'))
          .content!;
      // mock data is rendered in the body.
      expect(content.contains('CartMockData'), isTrue);
      expect(content.contains('ListView.builder'), isTrue);
      expect(content.contains('Container()'), isFalse);
      // The mock body never references viewState, so the declaration must
      // not be emitted — an unreferenced local would fail analysis with
      // `unused_local_variable`.
      expect(
        content.contains('viewState'),
        isFalse,
        reason: 'no unused viewState declaration when mock data renders',
      );

      final errors = syntaxErrors(content);
      expect(
        errors,
        isEmpty,
        reason:
            'state-aware view must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
    });

    test('custom (non-entity) view is unaffected — keeps the "is working" '
        'placeholder', () async {
      // Custom view: no entity, no VPCS.
      final plugin = ViewPlugin(
        outputDir: outputDir,
        options: const GeneratorOptions(dryRun: false, force: true),
      );
      final config = GeneratorConfig(
        name: 'Splash',
        methods: const [],
        generateView: true,
        generateVpcs: false,
        generateController: false,
        generatePresenter: false,
        outputDir: outputDir,
      );
      final files = await plugin.generate(config);

      final content = files.first.content!;
      expect(
        content.contains('is working!'),
        isTrue,
        reason: 'custom view keeps its placeholder body',
      );
      expect(
        content.contains('MockData'),
        isFalse,
        reason: 'custom view must not reference mock data',
      );
    });
  });
}

List<Diagnostic> syntaxErrors(String source) {
  final result = parseString(content: source, throwIfDiagnostics: false);
  return result.errors.cast<Diagnostic>();
}
